module.exports = {
    AccountComment: require("./acomments"),
    Account: require("./accounts"),
    Bans: require("./bans"),
    Comment: require("./comments"),
    Cpshare: require("./cpshares"),
    DailyFeature: require("./dailyFeature"),
    FriendReq: require("./friendReqs"),
    Friendship: require("./friendships"),
    Gauntlet: require("./gauntlets"),
    LevelScore: require("./levelScores"),
    MapPack: require("./mapPacks"),
    Message: require("./messages"),
    Quest: require("./quests"),
    Report: require("./reports"),
    RoleAssign: require("./roleAssign"),
    Song: require("./songs"),
    Suggest: require("./suggest"),
};